### ISSUE TITLE
Example claude_desktop_config?

### ISSUE THREAD

**Issue by svperfecta** [supercorp-ai/supergateway#1]
Hey Team - Any chance you have an example of what `claude_desktop_config.json`  would look like using this via HTTP.  Every example I can find of this file uses stdio (cannot find one... google fail)

**Comment by svperfecta** [comment]
Ahh, whoops.  https://github.com/orgs/modelcontextprotocol/discussions/91

**Comment by Nedomas** [comment]
good catch! 

For LLM UIs, the only ones that I know that support MCP on SSE are [LibreChat](https://www.librechat.ai/docs/configuration/librechat_yaml/object_structure/mcp_servers) and [Superinterface](https://superinterface.ai/blog/mcp). 

- LibreChat as direct replacement of Claude Desktop.
- Superinterface as the only way for web-based assistants to use MCP.
- You can also use mcp inspector to check that SSE is running.
